return {
	armca = {
		acceleration = 0.07,
		brakerate = 0.4275,
		buildcostenergy = 5000,
		buildcostmetal = 110,
		builddistance = 136,
		builder = true,
		shownanospray = false,
		buildpic = "ARMCA.DDS",
		buildtime = 8844,
		canfly = true,
		canmove = true,
		category = "ALL MOBILE NOTLAND NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 70,
		description = "Tech Level 1",
		energymake = 5,
		energystorage = 25,
		energyuse = 5,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 140,
		maxslope = 10,
		maxvelocity = 6.94,
		maxwaterdepth = 0,
		metalmake = 0.05,
		metalstorage = 25,
		name = "Construction Aircraft",
		objectname = "ARMCA",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 390,
		terraformspeed = 225,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 55,
		blocking = false,
		buildoptions = {
			"armsolar",
			"armwin",
			"armmex",
			"armestor",
			"armmstor",

			"armrad",
			"armmakr",
			"armlab",
			"armvp",
			"armap",

			"armadvsol",
			"armgeo",
			"armaap",
			"armsy",
			"armhp",

			"armeyes",
			"armllt",
			"armdrag",
			"armrl",
			"armdl",

			"armjamt",
			"armamex",
			"armclaw",
			"armbeamer",
			"armpacko",

			"armnanotc",
			"armhlt",
			"armguard",
			"armcir",
			"armjuno",
		},
		customparams = {
			wingsurface = 0.5,
			area_mex_def = "armmex",
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg3-builder",
				"deathceg2-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
