return {
	armresp = {
		acceleration = 0.07,
		brakerate = 0.4275,
		buildcostenergy = 4210,
		buildcostmetal = 118,
		builddistance = 136,
		builder = true,
		shownanospray = false,
		buildpic = "ARMRESP.PNG",
		buildtime = 5941,
		canfly = true,
		canmove = true,
		canassist = false,
		canresurrect = true,
		category = "ALL MOBILE NOTLAND NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 70,
		description = "Resurrect/Reclaim/Repair Plane",
		energyuse = 5,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 250,
		maxslope = 10,
		maxvelocity = 5.0,
		maxwaterdepth = 0,
		name = "Wasp",
		objectname = "ARMRESP",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 390,
		terraformspeed = 225,
		turninplaceanglelimit = 360,
		turnrate = 370,
		workertime = 100,
		reclaimspeed = 75,
		blocking = false,
		customparams = {
			wingsurface = 0.5,
			area_mex_def = "armmex",
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg3-builder",
				"deathceg2-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
