return {
	corca = {
		acceleration = 0.06,
		brakerate = 0.4275,
		buildcostenergy = 5000,
		buildcostmetal = 120,
		builddistance = 136,
		builder = true,
		shownanospray = false,
		buildpic = "CORCA.DDS",
		buildtime = 9286,
		canfly = true,
		canmove = true,
		category = "ALL MOBILE NOTLAND NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 75,
		description = "Tech Level 1",
		energymake = 5,
		energystorage = 25,
		energyuse = 5,
		explodeas = "smallexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 145,
		maxslope = 10,
		maxvelocity = 6.7,
		maxwaterdepth = 0,
		metalmake = 0.05,
		metalstorage = 25,
		name = "Construction Aircraft",
		objectname = "CORCA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 351,
		terraformspeed = 225,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 55,
		blocking = false,
		buildoptions = {
			"corsolar",
			"corwin",
			"cormex",
			"corestor",
			"cormstor",

			"corrad",
			"cormakr",
			"corlab",
			"corvp",
			"corap",

			"coradvsol",
			"corgeo",
			"coraap",
			"corsy",
			"corhp",

			"coreyes",
			"corllt",
			"cordrag",
			"corrl",
			"cordl",

			"corjamt",
			"corexp",
			"cormaw",
			"corplas",
			"cormadsam",

			"cornanotc",
			"corhlt",
			"corpun",
			"corerad",
			"corjuno",
		},
		customparams = {
			wingsurface = 0.5,
			area_mex_def = "cormex",
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2-builder",
				"deathceg3-builder",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
