return {
	armmyrm = {
		acceleration = 0.206,
		activateWhenBuilt = true,
		brakerate = 0.786,
		buildcostenergy = 54000,
		buildcostmetal = 4100,
		buildpic = "ARMMYRM.PNG",
		buildtime = 80470,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0.0 -2.0 -5",
		collisionvolumescales = "50.0 60.0 50.0",
		collisionvolumetype = "box",
		corpse = "DEAD",
		description = "Long Range Gauss Mech (2400 Radar Range)",
		explodeas = "hugeexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		mass = 200000,
		maxdamage = 14000,
		maxslope = 15,
		maxvelocity = 1.3,
		maxwaterdepth = 22,
		movementclass = "ATANK3",
		name = "Myrmidon",
		objectname = "ARMMYRM",
		radarDistance = 2400,
		radarEmitHeight = 300,
		seismicsignature = 0,
		selfdestructas = "hugeExplosionGenericSelfd",
		sightdistance = 450,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.518,
		turnrate = 347,
		upright = true,
		customparams = {
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-1.43661499023 -1.36986116943 12.126411438",
				collisionvolumescales = "61.6002807617 54.8114776611 71.5794219971",
				collisionvolumetype = "Box",
				damage = 1500,
				description = "Razorback Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 2325,
				object = "ARMRAZ_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 2000,
				description = "Razorback Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 930,
				object = "3X3B",
                collisionvolumescales = "55.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "krogok1",
			},
			select = {
				[1] = "servtny1",
			},
		},
		weapondefs = {
			armmyrm_gauss = {
				areaofeffect = 8,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:genericshellexplosion-small",
				impactonly = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				name = "GaussCannon",
				noselfdamage = true,
				range = 1700,
				reloadtime = 2.3,
				rgbColor = "1 1 1",
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.5,
				soundstart = "cannhvy1",
				stages = 150,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 3000,
				damage = {
					bombers = 35,
					default = 470,
					fighters = 35,
					subs = 5,
					vtol = 35,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "ARMMYRM_GAUSS",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
