return {
	coresupp = {
		buildangle = 16384,
		buildcostenergy = 2100,
		buildcostmetal = 205,
		buildpic = "CORESUPP.DDS",
		buildtime = 4075,
		canmove = true,
		category = "ALL WEAPON SHIP NOTSUB NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 -4 -1",
		collisionvolumescales = "20 20 55",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		description = "Assault Corvette",
		energymake = 3,
		explodeas = "mediumexplosiongeneric",
		floater = true,
		footprintx = 3,
		footprintz = 3,
		icontype = "sea",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 720,
		minwaterdepth = 12,
		movementclass = "BOAT43X3",
		name = "Supporter",
		nochasecategory = "UNDERWATER VTOL",
		objectname = "CORESUPP",
		seismicsignature = 0,
		selfdestructas = "mediumexplosiongenericSelfd",
		sightdistance = 320,
		waterline = 0,
		--move
		acceleration = 3.15/90,
		brakerate = 3.15/15,
		maxvelocity = 3.0,
		turninplace = true,
		turninplaceanglelimit = 110,
		turninplacespeedlimit = 0.64*3.15,
		turnrate = 425,
		--end move
		customparams = {
			tooltipWeapon = "Piercing Laser",
			weaponDamageRate = "2",
			paralyzeMultiplier = 0.4,
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "2.05702972412 -6.65740128174 -1.55792999268",
				collisionvolumescales = "37.2419281006 12.2129974365 67.4956207275",
				collisionvolumetype = "Box",
				damage = 150,
				description = "Supporter Wreckage",
				energy = 0.8*0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 0.8*191,
				object = "CORESUPP_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 250,
				description = "Supporter Heap",
				energy = 0.8*0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 0.8*91,
				object = "4X4B",
                collisionvolumescales = "85.0 14.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "shcormov",
			},
			select = {
				[1] = "shcorsel",
			},
		},
		weapondefs = {
			coresupp_laser = {
				areaofeffect = 20,
				avoidfeature = false,
				burnblow = true,
				collideenemy = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.2,
				energypershot = 10,
				explosiongenerator = "custom:laserhit-small-red",
				impactonly = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "PiercingLaser",
				noexplode = true,
				range = 320,
				reloadtime = 0.65,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrlit3",
				soundtrigger = 1,
				thickness = 1.5,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1370,
				damage = {
					default = 40,
					vtol = 10,
					subs = 10,
				},
			},
		},
		weapons = {
			[1] = {
				def = "CORESUPP_LASER",
				onlytargetcategory = "NOTSUB",
				maindir = "0 0 1",
				maxangledif = 285,
			},
			[2] = {
				def = "CORESUPP_LASER",
				onlytargetcategory = "NOTSUB",
				maindir = "0 0 -1",
				maxangledif = 285,
			},
		},
	},
}
