return {
	corprot = {
		acceleration = 0.057,
		brakerate = 0.18,
		buildcostenergy = 7137,
		buildcostmetal = 311,
		buildpic = "CORPROT.PNG",
		buildtime = 7340,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "30 15 32",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		description = "Support Assault Tank (700 Sight Range)",
		energymake = 0.5,
		energyuse = 0.5,
		explodeas = "smallexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maxdamage = 1421,
		maxslope = 10,
		maxvelocity = 2.3,
		maxwaterdepth = 12,
		movementclass = "TANK2",
		name = "Proteus",
		nochasecategory = "VTOL",
		objectname = "CORPROT",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 700,
		trackoffset = 5,
		trackstrength = 5,
		tracktype = "StdTank",
		trackwidth = 21,
		turninplace = true,
		turninplaceanglelimit = 110,
		turninplacespeedlimit = 1.98,
		turnrate = 350,
		script = "BASICTANKSCRIPT.LUA",
		customparams = {
			description_long = "",  
			--ANIMATION DATA
				--PIECENAMES HERE
					basename = "base",
					turretname = "turret",
					sleevename = "sleeve",
					cannon1name = "barrel",
					flare1name = "flare",
					cannon2name = nil, --optional (replace with nil)
					flare2name = nil, --optional (replace with nil)
				--SFXs HERE
					firingceg = "barrelshot-tiny",
					driftratio = "0.6", --How likely will the unit drift when performing turns?
					rockstrength = "0", --Howmuch will its weapon make it rock ?
					rockspeed = "0", -- More datas about rock(honestly you can keep 2 and 1 as default here)
					rockrestorespeed = "0", -- More datas about rock(honestly you can keep 2 and 1 as default here)
					cobkickbackrestorespeed = "3", --How fast will the cannon come back in position?
					kickback = "-2.4", --How much will the cannon kickback
				--AIMING HERE
					cobturretyspeed = "175", --turretSpeed as seen in COB script
					cobturretxspeed = "175", --turretSpeed as seen in COB script
					restoretime = "3000", --restore delay as seen in COB script
			},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 -0.0103445068359 -0.00248718261719",
				collisionvolumescales = "21.4374389648 12.6050109863 32.0003356934",
				collisionvolumetype = "Box",
				damage = 550,
				description = "Proteus Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 150,
				object = "CORPROT_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 225,
				description = "Proteus Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 75,
				object = "2X2F",
                collisionvolumescales = "35.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tcormove",
			},
			select = {
				[1] = "tcorsel",
			},
		},
		weapondefs = {
			cor_prot = {
				areaofeffect = 20,
				avoidfeature = false,
				--avoidfriendly = false,
				burnblow = true,
				collideenemy = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.2,
				energypershot = 10,
				explosiongenerator = "custom:genericshellexplosion-small",
				impactonly = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "PiercingLaser",
				noexplode = true,
				range = 550 + 50,
				reloadtime = 1.0,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrlit3",
				soundtrigger = 1,
				thickness = 1.5,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1500,
				damage = {
					default = 37,
					kbot = 54,
					tank = 54,
					hover = 54,
					vtol = 10,
					subs = 10,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COR_PROT",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
