return {
	corfing = {
		acceleration = 0.027,
		airsightdistance = 900,
		brakerate = 0.0495,
		buildcostenergy = 2340,
		buildcostmetal = 261,
		buildpic = "CORFING.PNG",
		buildtime = 3927,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 -6 1",
		collisionvolumescales = "34 18 43",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		description = "Salvo Rocket Launcher",
		energymake = 0.5,
		energyuse = 0.5,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maxdamage = 670,
		maxslope = 16,
		maxvelocity = 3.0,
		maxwaterdepth = 12,
		movementclass = "TANK3",
		name = "Scarfing",
		objectname = "CORFING",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 325,
		trackoffset = -6,
		trackstrength = 5,
		tracktype = "StdTank",
		trackwidth = 30,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.99,
		turnrate = 800,
		customparams = {
			description_long = "",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.41771697998 -0.356536877441 1.65004730225",
				collisionvolumescales = "31.3571624756 22.0425262451 48.4261016846",
				collisionvolumetype = "Box",
				damage = 672,
				description = "Slasher Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 100,
				object = "CORFING_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 336,
				description = "Slasher Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 46,
				object = "3X3F",
                collisionvolumescales = "55.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			 pieceExplosionGenerators = { 
				"deathceg2",
 				"deathceg3",
 				"deathceg4",
 			}, 
			explosiongenerators = {
				[1] = "custom:rocketflare",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vcormove",
			},
			select = {
				[1] = "vcorsel",
			},
		},
		weapondefs = {
			corfing_salvo = {
				areaofeffect = 200,
				avoidfeature = false,
				burst = 18,
				burstrate = 0.27,
				sprayAngle = 2000,
				commandfire = true,
		                cegTag = "fingrocketflare",
				model = "fingmissile",
				craterareaofeffect = 105,
				craterboost = 0,
				cratermult = 0,
				edgeEffectiveness = 1.0,
				explosiongenerator = "custom:genericshellexplosion-medium",
				gravityaffected = "true",
				hightrajectory = 1,
				myGravity = 0.27,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				name = "SalvoRocket",
				noselfdamage = true,
				range = 540,
				reloadtime = 24,
				rgbcolor = "1 1 0.47",
				soundhit = "xplosml3",
				soundhitwet = "splssml",
				soundhitwetvolume = 0.5,
				soundstart = "rapidrocket3",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 340,
				size = 1.7,
				stages = 1,
				damage = {
					default = 75,
					commanders = 200,
					kbot = 200,
					tank = 300,
					hover = 200,
				},
				customparams = {
					light_mult = "0.66", --used by light_effects widget
				},
			},
		},
		weapons = {
			[1] = {
				def = "CORFING_SALVO",
				maindir = "0 0 1",
				maxangledif = 180,
				onlytargetcategory = "",
			},
		},
	},
}
