return {
	corplas = {
		acceleration = 0,
		brakerate = 0,
		buildangle = 32768,
		buildcostenergy = 1700,
		buildcostmetal = 200,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 4,
		buildinggrounddecalsizey = 4,
		buildinggrounddecaltype = "corhllt_aoplane.dds",
		buildpic = "CORPLAS.PNG",
		buildtime = 5448,
		canrepeat = false,
		category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 1 -2",
		collisionvolumescales = "45 102 45",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		description = "Fire Barrier Cannon",
		energystorage = 60,
		explodeas = "mediumBuildingexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 1500,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Immolator",
		objectname = "CORPLAS",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 475,
		usebuildinggrounddecal = true,
		yardmap = "oooo",
		customparams = {
			tooltipWeapon = "Rapid Plasma",
			bar_collisionvolumeoffsets = "0 1 0",
			bar_collisionvolumescales = "32 100 32",
			removewait = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-10.5723800659 -3.06343876953 1.66596221924",
				collisionvolumescales = "35.5121612549 61.9105224609 33.3319244385",
				collisionvolumetype = "Box",
				damage = 900,
				description = "Immolator Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 6.5,
				hitdensity = 100,
				metal = 120,
				object = "CORPLAS_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 450,
				description = "Immolator Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 1,
				hitdensity = 100,
				metal = 48,
				object = "4X4D",
                collisionvolumescales = "85.0 14.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			core_immolator = {
				areaofeffect = 48,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				energypershot = 20,
				explosiongenerator = "custom:genericshellexplosion-small",
				firestarter = 100,
				gravityaffected = "true",
				impulsefactor = 1.97,
				mygravity = 0.01,
				name = "ImmolatorCannon",
				noselfdamage = true,
				range = 450,
				reloadtime = 0.3,
				size = 3.5,
				soundhit = "xplosml3",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.5,
				soundstart = "cannon1",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 277,
				damage = {
					bombers = 18,
					commanders = 100,
					default = 50,
					fighters = 18,
					subs = 5,
					vtol = 18,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "CORE_IMMOLATOR",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
