return {
	corsb = {
		acceleration = 0.2,
		brakerate = 0.045,
		buildcostenergy = 4440,
		buildcostmetal = 140,
		buildpic = "CORSB.PNG",
		buildtime = 4327,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL NOTLAND MOBILE WEAPON VTOL ANTIFLAME ANTIEMG ANTILASER NOTSUB NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 150,
		description = "Seaplane Bomber",
		energymake = 0.9,
		energyuse = 0.9,
		explodeas = "mediumExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 400,
		maxslope = 10,
		maxvelocity = 9.3,
		maxwaterdepth = 255,
		name = "Osprey",
		noautofire = true,
		nochasecategory = "VTOL",
		objectname = "CORSB",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 455,
		turnrate = 470,
		blocking = false,
		customparams = {
			tooltipWeapon = "Riot Cannon",
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
		weapondefs = {
			corlevlr_weapon = {
				areaofeffect = 144,
				avoidfeature = false,
				burnblow = true,
				craterareaofeffect = 144,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:genericshellexplosion-medium",
				impulsefactor = 1.8,
				name = "RiotCannon",
				noselfdamage = true,
				range = 230,
				reloadtime = 8,
				soundhit = "xplosml3",
				soundhitwet = "splsmed",
				soundhitwetvolume = 0.5,
				soundstart = "canlite1",
				turret = false,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					bombers = 27,
					default = 190,
					fighters = 27,
					subs = 5,
					vtol = 27,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "CORLEVLR_WEAPON",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
