return {
	corfmkr = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 2500,
		buildcostmetal = 1,
		buildpic = "CORFMKR.PNG",
		buildtime = 2682,
		canrepeat = false,
		cantBeTransported = false,
		--category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE",
		description = "Converts up to 77 energy into 0.55% of your team's metal extraction each second",
		explodeas = "largeBuildingExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		mass = 0, --for non-air transport
		maxdamage = 120,
		maxslope = 10,
		minwaterdepth = 11,
		floater = true,
		movementClass = "NANO",
		name = "Floating Energy Converter",
		objectname = "CORFMKR",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		waterline = 24,
		yardmap = "wwwwwwwww",
		customparams = {
			tooltipUpkeep = true,
			specialTooltip = "Can be transported by Air",
			removewait = true,
			removestop = true,
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			activate = "metlon2",
			canceldestruct = "cancel2",
			deactivate = "metloff2",
			underattack = "warning1",
			working = "metlrun2",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "metlon2",
			},
		},
	},
}
