return {
	coramph = {
		acceleration = 0.09,
		activatewhenbuilt = true,
		brakerate = 0.564,
		buildcostenergy = 9500,
		buildcostmetal = 320,
		buildpic = "CORAMPH.DDS",
		buildtime = 9650,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL NOTSHIP NOTAIR NOTHOVER NOTSUB SURFACE CANBEUW",
		collisionvolumeoffsets = "0 0 -7",
		collisionvolumescales = "32 29 32",
		collisionvolumetype = "CylY",
		corpse = "HEAP",
		description = "Medium Amphibious Kbot",
		energymake = 0.4,
		energyuse = 0.4,
		explodeas = "smallExplosionGeneric-phib",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 2100,
		maxslope = 14,
		maxvelocity = 1.85,
		movementclass = "AKBOT2",
		name = "Gimp",
		nochasecategory = "VTOL",
		objectname = "CORAMPH",
		radardistance = 300,
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-phib",
		sightdistance = 400,
		sonardistance = 300,
		sonarstealth = false,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.221,
		turnrate = 998,
		upright = true,
		customparams = {
			tooltipWeapon = "Heavy Laser",
			specialTooltip = "Can Attack underwater",
			techlevel = 2,
		},
		featuredefs = {
			heap = {
				blocking = false,
				category = "heaps",
				damage = 920,
				description = "Gimp Heap",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 114,
				object = "2X2D",
                collisionvolumescales = "35.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			coramph_laser = {
				areaofeffect = 12,
				avoidfeature = false,
				corethickness = 0.2,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.04,
				energypershot = 35,
				explosiongenerator = "custom:genericshellexplosion-small",
				firestarter = 90,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 300,
				reloadtime = 1.15,
				rgbcolor = "0 1 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrhvy3",
				soundtrigger = 1,
				targetmoveerror = 0.25,
				thickness = 3,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 700,
				damage = {
					bombers = 38,
					default = 150,
					fighters = 38,
					subs = 5,
					vtol = 38,
				},
			},
			coramph_sealaser = {
				areaofeffect = 12,
				avoidfeature = false,
				beamtime = 0.3,
				corethickness = 0.4,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 1,
				energyPerShot = 35,
				explosiongenerator = "custom:laserhit-small-blue",
				firestarter = 35,
				firesubmersed = true,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.3,
				laserflaresize = 7,
				name = "SeaLaser",
				noselfdamage = true,
				range = 300,
				reloadtime = 1.15,
				rgbcolor = "0.2 0.2 0.6",
				rgbcolor2 = "0.2 0.2 0.2",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "uwlasrfir1",
				soundtrigger = 1,
				targetmoveerror = 0.25,
				thickness = 5,
				tolerance = 10000,
				turret = true,
				waterweapon = true,
				weapontype = "BeamLaser",
				weaponvelocity = 700,
				damage = {
					default = 150,
					subs = 75,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "CORAMPH_LASER",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "CORAMPH_SEALASER",
				onlytargetcategory = "NOTAIR",
			},
		},
	},
}
