return {
	armscram = {
		activatewhenbuilt = true,
		buildcostenergy = 17347,
		buildcostmetal = 800,
		buildpic = "ARMSCRAM.PNG",
		buildtime = 11340,
		canCloak = true,
		cloakCost = 170,
		cloakCostMoving = 370,
		minCloakDistance = 170,
		decloakSpherical = false,
		canmove = true,
		category = "ALL NOTLAND MOBILE NOWEAPON NOTAIR NOTHOVER CANBEUW SURFACE",
		collisionvolumeoffsets = "0.5 0 0",
		collisionvolumescales = "20 15 64",
		collisionvolumetype = "box",
		corpse = "DEAD",
		description = "Sonar-Invisible Scout Sub",
		energymake = 0.5,
		energyuse = 0.5,
		explodeas = "mediumExplosionGeneric-uw",
		footprintx = 4,
		footprintz = 4,
		icontype = "sea",
		idleautoheal = 10,
		idletime = 900,
		maxdamage = 437,
		minwaterdepth = 20,
		movementclass = "UBOAT34X4",
		name = "Fibber",
		nochasecategory = "VTOL",
		objectname = "ARMSCRAM",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd-uw",
		sightdistance = 470,
		sonarStealth = true,
		--move
		brakerate =  2.80/20,
		acceleration = 2.80/150,
		maxvelocity = 3.4,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.64*2.80,
		turnrate = 337,	
		--end move
		upright = true,
		waterline = 40,
		customparams = {
			specialTooltip = "Can Cloak (170 Cost, 370 while moving)",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.712867736816 -4.88281237665e-09 -0.00479125976563",
				collisionvolumescales = "19.7231903076 16.8272399902 61.3809509277",
				collisionvolumetype = "Box",
				damage = 717,
				description = "Fibber Wreckage",
				energy = 0.8*0,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 0.8*681,
				object = "ARMSCRAM_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 2016,
				description = "Fibber Heap",
				energy = 0.8*0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 0.8*181,
				object = "2X2A",
                collisionvolumescales = "35.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "suarmmov",
			},
			select = {
				[1] = "watrjam1",
			},
		},
	},
}
