return {
	corcapt = {
		buildcostenergy = 4000,
		buildcostmetal = 170,
		buildtime = 3100,
		acceleration = 0.2,
		brakerate = 0.75,
		builder = true,
		builddistance = 110,
		buildRange3D = true,
		shownanospray = false,
		buildpic = "CORCAPT.PNG",
		canassist = false,
		canmove = true,
		canCapture = true,
		workerTime = 300,
		canRepair = false,
		canReclaim = false,
		category = "KBOT MOBILE ALL NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 -2 1",
		collisionvolumescales = "30.5 36 30.5",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		description = "Stealthy All-Terrain Capture Kbot",
		energymake = 1.75,
		energyuse = 1.75,
		explodeas = "smallbuilder",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 60,
		maxdamage = 147,
		maxslope = 14,
		maxvelocity = 1.7,
		maxwaterdepth = 22,
		movementclass = "TKBOT2",
		name = "Nipper",
		objectname = "CORCAPT",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "smallbuilderSelfd",
		sightdistance = 470,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.716,
		turnrate = 700,
		upright = true,
		customparams = {
			tooltipSight = true,
			specialTooltip = "Capture Speed: 300",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.248977661133 -1.21184884033 0.586555480957",
				collisionvolumescales = "33.9485473633 23.5305023193 36.0355987549",
				collisionvolumetype = "Box",
				damage = 794,
				description = "Nipper Wreckage",
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 72,
				object = "CORCAPT_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 394,
				description = "Nipper Heap",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 26,
				object = "2X2D",
                collisionvolumescales = "35.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg3",
				"deathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servtny1",
			},
			select = {
				[1] = "servtny1",
			},
		},
	},
}
