return {
	corgate = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 2048,
		buildcostenergy = 70000,
		buildcostmetal = 3000,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 8,
		buildinggrounddecalsizey = 8,
		buildinggrounddecaltype = "corgate_aoplane.dds",
		buildpic = "CORGATE.PNG",
		buildtime = 55000000,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 -4 1",
		collisionvolumescales = "57 38 57",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		description = "Teleportation Device",
		energystorage = 1500,
		explodeas = "energystorage",
		--footprintx = 5,
		--footprintz = 5,
		footprintx = 4,
		footprintz = 4,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 7200,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Gates",
		objectname = "CORGATE",
		onoffable = false,
		script = "CORGATE.LUA",
		seismicsignature = 0,
		selfdestructas = "energystorageSelfd",
		sightdistance = 273,
		transportCapacity = 100,
		transportSize = 4,
		transportUnloadMethod = 0,
		loadingRadius = 170,
		unloadSpread = 4,
		--usebuildinggrounddecal = true,
		yardmap = "oooooooooooooooo",
		customparams = {
			specialTooltip = "Maximum 2 Gates per team",
			specialTooltip2 = "Commanders have 1000x Build Speed towards it",
			teleportationGates = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 -0.00271934814453 -1.05072021484",
				collisionvolumescales = "65.7474060059 27.1259613037 55.6685791016",
				collisionvolumetype = "Box",
				damage = 1900,
				description = "Overseer Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 2000,
				--object = "CORBUILD_DEAD",
				object = "CORGATE_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 960,
				description = "Overseer Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 800,
				object = "2X2E",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "drone1",
			},
			select = {
				[1] = "drone1",
			},
		},
	},
}
